# -*- coding: utf-8 -*-
"""big_assign4_nofill.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yGskeKpcDvaWOuF9Uyr0o9sO_95ucO5V

1.아래와 같은 구조를 갖는  데이터 프레임에서    (원본 객체 변경: iplace=True)  
1) 이름을 index로 설정하고  
2) '취미' 열을 삭제 하고    
3) '나라' 행을 삭제 하고    
4) '지민' 행을 이름 인덱스를 이용하여  추가 하여  '16, 중등, 효성'    데이터를 저장하고  
5) column 이름 '학교'를 '교명'으로 바꾸고  
6) 우석과 인아의 교명을 선경1, 한국1로 변경하고  
7) 나이 기준 어린  순으로 행을 정렬 한 후  
8) '국적'열을 추가 한 후 모두 '한국' 으로 저장 한 후  
9) print하는 code를 작성 하시오  


|이름|나이|구분|취미|학교 |
|-|-|-|-|-|
|우석|17|고등|독서|선경|
|인아|14|중등|산책|한국|
|나라|12|초등|축구|우성|
|민정|19|고등|독서|효성|
|서준|15|중등|농구|상성|
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
#과제 1
import pandas as pd
student_data = {'이름':['우석', '인아', '나라', '민정', '서준'],
                '나이': [17,14,12,19,15], 
                '구분':['고등','중등','초등','고등','중등'], 
                '취미':['독서','산책','축구', '독서','농구'], 
                '학교':['선경','한국','우성','효성','상성'] }    

# 1) 이름을 index로 설정
df = pd.DataFrame(student_data, index=student_data['이름'])
df.drop('이름', axis=1, inplace=True)
print('1) 이름을 index로 설정: \n', df)
print("\n-----------------------------\n")

# 2) '취미' 열 삭제
df.drop('취미', axis=1, inplace=True)
print('2) 취미 열 삭제: \n', df)
print("\n-----------------------------\n")

# 3) '나라' 행 삭제
df.drop('나라', axis=0, inplace=True)
print('3) 나라 행 삭제: \n', df)
print("\n-----------------------------\n")

# 4) '지민' 행을 이름 인덱스를 이용하여 추가 하여 '16, 중등, 효성' 데이터를 저장
df.loc['지민'] = [16, '중등', '효성']
print('4) 지민 행 추가: \n', df)
print("\n-----------------------------\n")

# 5) column 이름 '학교'를 '교명'으로 변경
df.rename(columns={'학교':'교명'}, inplace=True)
print('5) column 이름 학교를 교명으로 변경: \n', df)
print("\n-----------------------------\n")

# 6) 우석과 인아의 교명을 선경1, 한국1로 변경
# df.loc['우석']['교명'] = '선경1'
# df.loc['인아']['교명'] = '한국1'
df.loc[['우석', '인아'], ['교명']] = ['선경1', '한국1']
print('6) 우석과 인아의 교명을 선경1, 한국1로 변경: \n', df)
print("\n-----------------------------\n")

# 7) 나이 기준 어린 순으로 행을 정렬
df = df.sort_values(by='나이', ascending = True)
print('7) 나이 기준 어린 순으로 행을 정렬: \n', df)
print("\n-----------------------------\n")

# 8) '국적' 열을 추가한 뒤, 모두 '한국'으로 저장
df['국적'] = '한국'
print('8) 국적 열을 추가한 뒤, 모두 한국으로 저장: \n', df)
print("\n-----------------------------\n")

# 9) 출력..
print('9) 출력: \n', df)

"""2.아래와 같은 구조를 갖는  데이터 프레임에서    (원본 객체 변경: iplace=True)  
1) '인문' 열을 추가 하여 영어와 국어 성적의 합계를 저장하고  
2) '과학' 열을 추가 하여 물리와 화학 성적의 합계를 저장하고  
3)  과학 성적으로 내림 차순으로 정렬하고  
4) print하는 code를 작성하시오.   


|이름|국어|영어|물리|화학|
|-|-|-|-|-|
|우석|90|85|70|50|
|인아|80|90|80|70|
|나라|75|85|80|90|
|민정|90|95|90|100|

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
#과제 2
import pandas as pd
student_data = {'이름':['우석', '인아', '나라', '민정'],
                '국어':[90,80,75,90], 
                '영어':[85,90,85,95], 
                '물리':[70,80,80,90], 
                '화학':[50,70,90,100] }    
df=pd.DataFrame(student_data)
print(df)
print("\n-----------------------------\n")

# 1) '인문' 열을 추가하여 영어와 국어 성적의 합계를 저장
df['인문'] = df['국어'] + df['영어']
print('1) 인문 열을 추가하여 영어와 국어 성적의 합계를 저장: \n', df)
print("\n-----------------------------\n")

# 2) '과학' 열을 추가하여 물리와 화학 성적의 합계를 저장
df['과학'] = df['물리'] + df['화학']
print('2) 과학 열을 추가하여 영어와 국어 성적의 합계를 저장: \n', df)
print("\n-----------------------------\n")

# 3) 과학 성적으로 내림차순으로 정렬
df = df.sort_values('과학', ascending = False)
print('3) 과학 성적으로 내림차순 정렬: \n', df)
print("\n-----------------------------\n")

# 4) print..
print(df)

"""3.1) iris3.csv 파일을 읽고 (첫번째 행을 column 이름으로)  
2) column 이름을 'feat1','feat2','feat3','feat4','name'으로 변경하고  
3) 처음 3개 행을 print하고  
4) 요약 정보를 print하고  
5) 통계 정보를 print하고  
6) 각 열 데이터의 고유값 개수를 print하고  
7) 'feat2' 열의 최대값 print  
8) 'feat4' 열의 표준 편차 print   
9) 'feat1'과 'feat3'의 상관계수를 출력하는 코드를 작성 하시오.   
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
#과제 3
import pandas as pd

# 1) iris3.csv 파일을 읽고 첫 번째 행을 column 이름으로
df = pd.read_csv('/content/iris3.csv') # default header=0
print(df)
print("\n-----------------------------\n")

# 2) column 이름을 'feat1', 'feat2', 'feat3', 'feat4', 'name'으로 변경
df.rename(columns={'sepal_length':'feat1',
                   'sepal_width':'feat2',
                   'petal_length':'feat3',
                   'petal_width':'feat4',
                   'species':'name'}, inplace=True)
print('2) column 이름 변경: \n', df)
print("\n-----------------------------\n")

# 3) 처음 3개의 행을 출력
print('3) 처음 3개의 행을 출력: \n', df.head(3)) # default = 5
print("\n-----------------------------\n")

# 4) 요약 정보를 출력
# df의 모양과 크기 확인: (행의 개수, 열의 개수)를 튜플로 반환
print('4) 요약 정보를 출력: \n', df.shape)
print("\n-----------------------------\n")

# 5) 통계 정보를 출력
print('5) 통계 정보를 출력: \n', df.info())
print("\n-----------------------------\n")

# 6) 각 열 데이터의 고유값 개수를 출력
# print('각 열 데이터 개수: \n', df.count()) # -> 각 열의 데이터 개수
print('6) 각 열 데이터의 고유값 개수: \n', df.value_counts())
print("\n-----------------------------\n")

# 7) 'feat2'열의 최대값
print('7) feat2 열의 최대값: \n', df['feat2'].max())
print("\n-----------------------------\n")

# 8) 'feat4' 열의 표준 편차
print('8) feat4 열의 표준 편차: \n', df['feat4'].std())
print("\n-----------------------------\n")

# 9) 'feat1'과 'feat3'의 상관계수
print('9) feat1과 feat3의 상관계수: \n', df[['feat1', 'feat3']].corr())

"""4.code에서 정의한 데이터에서   
1) 하나라도 NaN이 있는 행은 삭제하고 print하는 code  (df1에 저장 후 print)    
2) 모든 값이  NaN인  행을 삭제하고 print하는 code  (df2에 저장 후 print)   
3) NaN이 포함된 행을 삭제할때 데이터가 4개 이상 있어야 남기도록 하고  (df3)   print하는 code를 작성 하시오 
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
#과제 4
import pandas as pd

import numpy as np

raw_data = {'name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'], 
            'age': [42, np.nan, 36, np.nan, 73], 
            'math': [4, np.nan, np.nan, 2, 3],
            'physics': [25, np.nan, np.nan, 62, 70],
             'korean': [25, np.nan, np.nan, 62, 70]}

df = pd.DataFrame(raw_data)
print(df)
print("\n-----------------------------\n")

# 1) 하나라도 NaN이 있는 행은 삭제
df1=df[:]
df1 = df1.dropna()
print('1) 하나라도 NaN이 있는 행은 삭제: \n', df1)
print("\n-----------------------------\n")

# 2) 모든 값이 NaN인 행을 삭제
df2=df[:]
df2 = df2.dropna(how='all')
print('2) 모든 값이 NaN인 행을 삭제: \n', df2)
print("\n-----------------------------\n")

# 3) NaN이 포함된 행을 삭제할 때 데이터가 4개 이상 있어야 남기고 출력
df3=df[:]
df3 = df3.dropna(axis=0, thresh=4)
print('3) NaN이 포함된 행을 삭제할 때 데이터가 4개 이상 있어야 남기고 출력: \n', df)

"""5.1) 'exam1.csv'파일을 읽고 (첫번째 행이 열이름이 되도록)   
2) english의 결측치는 0으로 치환하고     
3) math의 결측치는 math의 평균 값으로 치환하고   
4) nclass의 결측치는 앞에 값으로 치환하고  
5) print하는 code를 작성하시오  
(inplace=True 사용)  




"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
#과제 5
import pandas as pd

# 1) 'exam1.csv' 파일을 읽고 첫 번째 행이 열 이름이 되도록 설정
df = pd.read_csv('/content/exam1.csv', header=0)
print('1) exam1.csv 파일을 읽고 첫 번째 행이 열 이름이 되도록 설정: \n', df)
print("\n-----------------------------\n")

# 2) english의 결축치는 0으로 치환
df['english'].fillna(0, inplace=True)
print('2) english의 결축치는 0으로 치환: \n', df)
print("\n-----------------------------\n")

# 3) math의 결축치는 math의 평균 값으로 치환
mean_math = df['math'].mean()
df['math'].fillna(mean_math, inplace=True)
print('3) math의 결축치는 math의 평균 값으로 치환: \n', df)
print("\n-----------------------------\n")

# 4) nclass의 결축치는 앞에 값으로 치환
# .fillna(method = 'ffill', inplace = True) -> 바로 앞에 있는 값으로 치환
# .fillna(method = 'bfill', inplace = True) -> 바로 뒤에 있는 값으로 치환
df['nclass'].fillna(method = 'ffill', inplace=True)
print('4) nclass의 결축치는 앞에 값으로 치환: \n', df)
print("\n-----------------------------\n")

# 5) 프린트
print(df)

"""6.아래 code에서 정의하는 데이터 프레임에서    
1) 중복 행을 제거 하고 print하는 code(df1)  
2) c1,c3을 기준으로 중복행을 제거 하고 print하는 code(df2)  
를 작성 하시오. 

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
#과제 6
import pandas as pd

df=pd.DataFrame({'c1':['a','a','b','a','b'],
                 'c2':[2,1,2,1,2],
                 'c3':[1,1,2,2,2]})
print(df)
print("\n-----------------------------\n")

# 1) 중복 행을 제거하고 출력
df1 = df.drop_duplicates()
print('1) 중복 행을 제거: \n', df1)
print("\n-----------------------------\n")

# 2) c1, c3을 기준으로 중복행을 제거하고 print
df2 = df.drop_duplicates(subset=['c1', 'c3'])
print('2) c1, c3을 기준으로 중복행을 제거: \n', df2)

"""7.1) wine1.cse 파일을 읽고 (첫행부터 데이터로 읽음)  
2) column 이름을 'country', 'year','feat1','fest2','fest3','feat4'로 지정하고  
3) country의 누락 데이터는 france로 저장하고  
4) feat1, feat2, feat3, feat4의 누락 데이터는 각 열의 평균으로 저장하고  
5) 'country','year' 기준으로 중복데이터를 제거 하고  
6) 'feat1-2' 열을 추가 하여 feat1과 feat2의 핪의 값을 저장하고  
7) 'year'를 기준으로 오름 차순으로 출력하는 code를 작성 하시오.


"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
#과제 7
import pandas as pd

# 1) wine1.csv 파일을 읽고 첫 행부터 데이터로 읽음
df = pd.read_csv('/content/wine1.csv', header = None)
print('1) wine1.csv 파일을 읽고 첫 행부터 데이터로 읽음: \n', df)
print("\n-----------------------------\n")

# 2) column 이름을 'country', 'year', 'feat1', 'feat2', 'feat3','feat4'로 지정
df.columns=['country', 'year', 'feat1', 'feat2', 'feat3', 'feat4']
print('2) column 이름 지정: \n', df)
print("\n-----------------------------\n")

# 3) country의 누락 데이터는 france로 저장
df['country'].fillna('france', inplace=True)
print('3) country의 누락 데이터는 france로 저장: \n', df)
print("\n-----------------------------\n")

# 4) feat1, feat2, feat3, feat4의 누락 데이터는 각 열의 평균으로 저장
# feat1_mean = df['feat1'].mean()
# feat2_mean = df['feat2'].mean()
# feat3_mean = df['feat3'].mean()
# feat4_mean = df['feat4'].mean()
# df['feat1'].fillna(feat1_mean, inplace=True)
# df['feat2'].fillna(feat2_mean, inplace=True)
# df['feat3'].fillna(feat3_mean, inplace=True)
# df['feat4'].fillna(feat4_mean, inplace=True)

for i in ['feat1', 'feat2', 'feat3', 'feat4']:
  df[i].fillna(df[i].mean(), inplace=True)

print('4) 누락 데이터는 각 열의평균으로 저장: \n', df)
print("\n-----------------------------\n")

# 5) 'country','year' 기준으로 중복데이터를 제거
df = df.drop_duplicates(subset=['country', 'year'])
print('5) country, year 기준으로 중복 데이터를 제거: \n', df)
print("\n-----------------------------\n")

# 6) 'feat1-2' 열을 추가 하여 feat1과 feat2의 합의 값을 저장
df['feat1-2'] = df['feat1'] + df['feat2']
print('6) feat1-2 열을 추가하여 feat1과 feat2의 합의 값을 저장: \n', df)
print("\n-----------------------------\n")

# 7) 'year'를 기준으로 오름 차순으로 출력
df = df.sort_values('year', ascending = True)
print('7) year를 기준으로 오름차순으로 출력: \n', df)